### ISSUE TITLE
Automatic Reloading 

### ISSUE THREAD

**Issue by k3tu1** [ShashwatMittal/Facebook-Album-Browser#1]
whenever i click on login button it popup window  for facebook permission when i click on ok , box is not disappearing and page continuously reloading or redirecting to home page
plz help me asps!     
OR 
suggest me where i can change in ur file and which file i need to add 
i already add my app_id and key what else i should do ?

**Comment by ShashwatMittal** [comment]
I could not reproduce this issue on my end. Facebook permission and login are working perfectly fine for me. The page redirection and Popup logic are both implemented in ```index.php``` as well as ```callback.php``` files.
